---
name: ci

# on:
#   push:
#
# jobs:
#   bake:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v5
#       - uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
#           password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
#       - uses: docker/setup-buildx-action@v3
#       - uses: docker/bake-action@v6
#         with:
#           source: .
#           push: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker-bake.hcl"
      - "**/Dockerfile*"
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: docker/bake-action/subaction/matrix@v6

  build:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      # - name: generate docker metadata
      #   id: docker-meta
      #   uses: docker/metadata-action@v5

      # - name: generate github metadata
      #   id: github-meta
      #   uses: dockerbakery/github-metadata-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: build and push
        uses: docker/bake-action@v6
        with:
          targets: ${{ matrix.target }}
          push: ${{ github.event_name != 'pull_request' }}
          files: |
            ./docker-bake.hcl
          #   cwd://${{ steps.docker-meta.outputs.bake-file-labels }}
          #   cwd://${{ steps.docker-meta.outputs.bake-file-annotations }}
          #   cwd://${{ steps.github-meta.outputs.bake-file }}
          # set: |
          #   *.cache-from=type=gha
          #   *.cache-to=type=gha,mode=max
