---
name: ci

on:
  push:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v6
        with:
          source: ./mise
          push: true
